version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voltride-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRAMEWORK=express # or fastify
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/voltride?schema=public
      - MONGODB_URI=mongodb://mongo:27017/voltride
    depends_on:
      - postgres
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - voltride-network
    command: sh -c "./wait-for-it.sh postgres:5432 -t 60 -- node dist/main.js"

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: voltride-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voltride
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - voltride-network

  # MongoDB database
  mongo:
    image: mongo:6-jammy
    container_name: voltride-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=voltride
    volumes:
      - mongo-data:/data/db
    networks:
      - voltride-network

  # pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4
    container_name: voltride-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@voltride.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - voltride-network

  # Mongo Express for MongoDB management
  mongo-express:
    image: mongo-express
    container_name: voltride-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - voltride-network

volumes:
  postgres-data:
  mongo-data:
  pgadmin-data:

networks:
  voltride-network:
    driver: bridge
