version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/voltride
      - MONGODB_URI=mongodb://mongodb:27017/voltride
    depends_on:
      - postgres
      - mongodb
    networks:
      - voltride-network
    volumes:
      - ./backend:/app
    command: >
      sh -c "
      ./wait-for-it.sh postgres:5432 -- 
      npx prisma generate --schema prisma/postgres/schema.prisma && 
      npx prisma migrate dev --schema prisma/postgres/schema.prisma --name init && 
      npm run build && 
      npm start"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voltride
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - voltride-network

  mongodb:
    image: mongo:6
    command: mongod --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zstd
    environment:
      - MONGO_INITDB_DATABASE=voltride
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - voltride-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - voltride-network

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - voltride-network

volumes:
  postgres-data:
  mongodb-data:

networks:
  voltride-network:
    driver: bridge
